name: Codex Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codex-job:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Checkout Et
        uses: actions/checkout@v3

      - name: Node Kur (örnek)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Gerekli Paketleri Kur
        run: npm install

      - name: Codex Script Çalıştır (örnek)
        run: npm run codex
